app1/urls.py
from django.urls import path
from app1.views import *
app_name='Bramhi'
urlpatterns=[
    path('gajala/',gajala,name='gajala'),
]

project3/urls.py
from django.contrib import admin
from django.urls import path,include
import app1
from app2.views import *


urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('venky/',venky,name='venky'),
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.
def gajala(request):
    return render(request,'gajala.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def venky(request):
    return render(request,'venky.html')

templates/gajala.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>ILAKHATHA MAFIYA</h1>
        <h2><a herf="{url 'venky'%}">venky.....</a></h2>

    </center>
</body>
</html>

templates/venky.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>Paadu gajala....</h1>
        <h2> <a href="{% url 'Bramhi:gajala'%}">Bramhi</a></h2>
    </center>
</body>
</html>